default: &default
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: 123

development:
  <<: *default
  database: postgres

test:
  <<: *default
  database: postgres

production:
  <<: *default
  database: db/production.sqlite3
